# Importing relevant libraries

In [33]:
import numpy as np
import pandas as pd                                                                                                                                                                                                                                
import seaborn as sns
import matplotlib.pyplot as plt
import statsmodels.api as sm

from sklearn.linear_model import LinearRegression

In [34]:
Energy = pd.read_csv(r"C:\Users\RPN\Desktop\Energy.csv")
Energy

,date,Appliances,lights,T1,RH_1,T2,RH_2,T3,RH_3,T4,...,T9,RH_9,T_out,Press_mm_hg,RH_out,Windspeed,Visibility,Tdewpoint,rv1,rv2
0,2016-01-11 17:00:00,60,30,19.890000,47.596667,19.200000,44.790000,19.790000,44.730000,19.000000,...,17.033333,45.5300,6.600000,733.5,92.000000,7.000000,63.000000,5.300000,13.275433,13.275433
1,2016-01-11 17:10:00,60,30,19.890000,46.693333,19.200000,44.722500,19.790000,44.790000,19.000000,...,17.066667,45.5600,6.483333,733.6,92.000000,6.666667,59.166667,5.200000,18.606195,18.606195
2,2016-01-11 17:20:00,50,30,19.890000,46.300000,19.200000,44.626667,19.790000,44.933333,18.926667,...,17.000000,45.5000,6.366667,733.7,92.000000,6.333333,55.333333,5.100000,28.642668,28.642668
3,2016-01-11 17:30:00,50,40,19.890000,46.066667,19.200000,44.590000,19.790000,45.000000,18.890000,...,17.000000,45.4000,6.250000,733.8,92.000000,6.000000,51.500000,5.000000,45.410389,45.410389
4,2016-01-11 17:40:00,60,40,19.890000,46.333333,19.200000,44.530000,19.790000,45.000000,18.890000,...,17.000000,45.4000,6.133333,733.9,92.000000,5.666667,47.666667,4.900000,10.084097,10.084097
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19730,2016-05-27 17:20:00,100,0,25.566667,46.560000,25.890000,42.025714,27.200000,41.163333,24.700000,...,23.200000,46.7900,22.733333,755.2,55.666667,3.333333,23.666667,13.333333,43.096812,43.096812
19731,2016-05-27 17:30:00,90,0,25.500000,46.500000,25.754000,42.080000,27.133333,41.223333,24.700000,...,23.200000,46.7900,22.600000,755.2,56.000000,3.500000,24.500000,13.300000,49.282940,49.282940
19732,2016-05-27 17:40:00,270,10,25.500000,46.596667,25.628571,42.768571,27.050000,41.690000,24.700000,...,23.200000,46.7900,22.466667,755.2,56.333333,3.666667,25.333333,13.266667,29.199117,29.199117
19733,2016-05-27 17:50:00,420,10,25.500000,46.990000,25.414000,43.036000,26.890000,41.290000,24.700000,...,23.200000,46.8175,22.333333,755.2,56.666667,3.833333,26.166667,13.233333,6.322784,6.322784
19734,2016-05-27 18:00:00,430,10,25.500000,46.600000,25.264286,42.971429,26.823333,41.156667,24.700000,...,23.200000,46.8450,22.200000,755.2,57.000000,4.000000,27.000000,13.200000,34.118851,34.118851

# Removing date and light from the data given

In [35]:
Energy = Energy.drop(['date', 'lights'], axis = 1)
Energy.describe()

,Appliances,T1,RH_1,T2,RH_2,T3,RH_3,T4,RH_4,T5,...,T9,RH_9,T_out,Press_mm_hg,RH_out,Windspeed,Visibility,Tdewpoint,rv1,rv2
count,19735.000000,19735.000000,19735.000000,19735.000000,19735.000000,19735.000000,19735.000000,19735.000000,19735.000000,19735.000000,...,19735.000000,19735.000000,19735.000000,19735.000000,19735.000000,19735.000000,19735.000000,19735.000000,19735.000000,19735.000000
mean,97.694958,21.686571,40.259739,20.341219,40.420420,22.267611,39.242500,20.855335,39.026904,19.592106,...,19.485828,41.552401,7.411665,755.522602,79.750418,4.039752,38.330834,3.760707,24.988033,24.988033
std,102.524891,1.606066,3.979299,2.192974,4.069813,2.006111,3.254576,2.042884,4.341321,1.844623,...,2.014712,4.151497,5.317409,7.399441,14.901088,2.451221,11.794719,4.194648,14.496634,14.496634
min,10.000000,16.790000,27.023333,16.100000,20.463333,17.200000,28.766667,15.100000,27.660000,15.330000,...,14.890000,29.166667,-5.000000,729.300000,24.000000,0.000000,1.000000,-6.600000,0.005322,0.005322
25%,50.000000,20.760000,37.333333,18.790000,37.900000,20.790000,36.900000,19.530000,35.530000,18.277500,...,18.000000,38.500000,3.666667,750.933333,70.333333,2.000000,29.000000,0.900000,12.497889,12.497889
50%,60.000000,21.600000,39.656667,20.000000,40.500000,22.100000,38.530000,20.666667,38.400000,19.390000,...,19.390000,40.900000,6.916667,756.100000,83.666667,3.666667,40.000000,3.433333,24.897653,24.897653
75%,100.000000,22.600000,43.066667,21.500000,43.260000,23.290000,41.760000,22.100000,42.156667,20.619643,...,20.600000,44.338095,10.408333,760.933333,91.666667,5.500000,40.000000,6.566667,37.583769,37.583769
max,1080.000000,26.260000,63.360000,29.856667,56.026667,29.236000,50.163333,26.200000,51.090000,25.795000,...,24.500000,53.326667,26.100000,772.300000,100.000000,14.000000,66.000000,15.500000,49.996530,49.996530

# Training and Testing the Data

In [36]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
scalerfit = scaler.fit_transform(Energy)

In [37]:
normalised_Energy = pd.DataFrame((scalerfit), columns = Energy.columns)
features_Energy = normalised_Energy.drop(columns=['Appliances'])
heating_target = normalised_Energy['Appliances']

In [38]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(features_Energy, heating_target, test_size=0.3, random_state=42)

In [39]:
linear_model = LinearRegression()
linear_model.fit(x_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [40]:
predicted_values=linear_model.predict(x_test)

#                                 QUESTION 13 - 15

# Calculating the Mean Absolute Error

In [41]:
from sklearn.metrics import mean_absolute_error
mae = mean_absolute_error(y_test, predicted_values)
round(mae, 3)

0.05

# Calculating the residual sum of square

In [42]:
rss = np.sum(np.square(y_test - predicted_values))
round(rss, 3)

45.348

# Calculaing the Root Mean Squared Error

In [43]:
from sklearn.metrics import mean_squared_error
rmse = np.sqrt(mean_squared_error(y_test, predicted_values))
round(rmse, 3)

0.088

# Calculating the Coefficient of Determination

In [44]:
from sklearn.metrics import r2_score
r2_score=r2_score(y_test, predicted_values)
round(r2_score, 3)

0.149

# QUESTION 17 - 19

# Finding the Regression model using the RIDGE regression and LASSO regression

In [45]:
def get_weights_Energy(model, feat, col_name):
    weights = pd.Series(model.coef_, feat.columns).sort_values()
    weights_Energy = pd.DataFrame(weights).reset_index()
    weights_Energy.columns = ['Features', col_name]
    weights_Energy[col_name].round(3)
    return weights_Energy

In [46]:
from sklearn.linear_model import Ridge
ridge_reg = Ridge(alpha=0.5)
ridge_reg.fit(x_train, y_train)

Ridge(alpha=0.5, copy_X=True, fit_intercept=True, max_iter=None,
      normalize=False, random_state=None, solver='auto', tol=0.001)

In [47]:
from sklearn.linear_model import Lasso
lasso_reg = Lasso(alpha=0.001)
lasso_reg.fit(x_train, y_train)

Lasso(alpha=0.001, copy_X=True, fit_intercept=True, max_iter=1000,
      normalize=False, positive=False, precompute=False, random_state=None,
      selection='cyclic', tol=0.0001, warm_start=False)

In [48]:
linear_model_weights = get_weights_Energy(linear_model, x_train, 'Linear_Model_Weight')
ridge_weights_Energy = get_weights_Energy(ridge_reg, x_train, 'Ridge_Weight')
lasso_weights_Energy = get_weights_Energy(lasso_reg, x_train, 'Lasso_weight')

In [49]:
final_weights = pd.merge(linear_model_weights, ridge_weights_Energy, on='Features')
final_weights = pd.merge(final_weights, lasso_weights_Energy, on='Features')

In [50]:
final_weights

       Features  Linear_Model_Weight  Ridge_Weight  Lasso_weight
0          RH_2            -0.456698     -0.401134     -0.000000
1         T_out            -0.321860     -0.250765      0.000000
2            T2            -0.236178     -0.193880      0.000000
3            T9            -0.189941     -0.188584     -0.000000
4          RH_8            -0.157595     -0.156596     -0.000110
5        RH_out            -0.077671     -0.050541     -0.049557
6          RH_7            -0.044614     -0.046291     -0.000000
7          RH_9            -0.039800     -0.041701     -0.000000
8            T5            -0.015657     -0.020727     -0.000000
9            T1            -0.003281     -0.021549      0.000000
10          rv2             0.000770      0.000743     -0.000000
11          rv1             0.000770      0.000743     -0.000000
12  Press_mm_hg             0.006839      0.006516     -0.000000
13           T7             0.010319      0.010021     -0.000000
14   Visibility             0.012307      0.012032      0.000000
15         RH_5             0.016006      0.016176      0.000000
16         RH_4             0.026386      0.024168      0.000000
17           T4             0.028981      0.027006     -0.000000
18    Windspeed             0.029183      0.030463      0.002912
19         RH_6             0.038049      0.035023     -0.000000
20         RH_3             0.096048      0.094976      0.000000
21           T8             0.101995      0.100754      0.000000
22    Tdewpoint             0.117758      0.076668      0.000000
23           T6             0.236425      0.213316      0.000000
24           T3             0.290627      0.287408      0.000000
25         RH_1             0.553547      0.511932      0.017880

# With the alpha as 0.4, the output remains the same

In [51]:
def get_weights_Energy(model, feat, col_name):
    weights = pd.Series(model.coef_, feat.columns).sort_values()
    weights_Energy = pd.DataFrame(weights).reset_index()
    weights_Energy.columns = ['Features', col_name]
    weights_Energy[col_name].round(3)
    return weights_Energy

In [52]:
from sklearn.linear_model import Ridge
ridge_reg = Ridge(alpha=0.4)
ridge_reg.fit(x_train, y_train)

Ridge(alpha=0.4, copy_X=True, fit_intercept=True, max_iter=None,
      normalize=False, random_state=None, solver='auto', tol=0.001)

In [53]:
from sklearn.linear_model import Lasso
lasso_reg = Lasso(alpha=0.001)
lasso_reg.fit(x_train, y_train)

Lasso(alpha=0.001, copy_X=True, fit_intercept=True, max_iter=1000,
      normalize=False, positive=False, precompute=False, random_state=None,
      selection='cyclic', tol=0.0001, warm_start=False)

In [54]:
linear_model_weights = get_weights_Energy(linear_model, x_train, 'Linear_Model_Weight')
ridge_weights_Energy = get_weights_Energy(ridge_reg, x_train, 'Ridge_Weight')
lasso_weights_Energy = get_weights_Energy(lasso_reg, x_train, 'Lasso_weight')

In [55]:
final_weights = pd.merge(linear_model_weights, ridge_weights_Energy, on='Features')
final_weights = pd.merge(final_weights, lasso_weights_Energy, on='Features')

In [56]:
final_weights

       Features  Linear_Model_Weight  Ridge_Weight  Lasso_weight
0          RH_2            -0.456698     -0.411071     -0.000000
1         T_out            -0.321860     -0.262172      0.000000
2            T2            -0.236178     -0.201397      0.000000
3            T9            -0.189941     -0.188916     -0.000000
4          RH_8            -0.157595     -0.156830     -0.000110
5        RH_out            -0.077671     -0.054724     -0.049557
6          RH_7            -0.044614     -0.045977     -0.000000
7          RH_9            -0.039800     -0.041367     -0.000000
8            T5            -0.015657     -0.019853     -0.000000
9            T1            -0.003281     -0.018406      0.000000
10          rv2             0.000770      0.000748     -0.000000
11          rv1             0.000770      0.000748     -0.000000
12  Press_mm_hg             0.006839      0.006584     -0.000000
13           T7             0.010319      0.010098     -0.000000
14   Visibility             0.012307      0.012076      0.000000
15         RH_5             0.016006      0.016152      0.000000
16         RH_4             0.026386      0.024579      0.000000
17           T4             0.028981      0.027384     -0.000000
18    Windspeed             0.029183      0.030268      0.002912
19         RH_6             0.038049      0.035519     -0.000000
20         RH_3             0.096048      0.095135      0.000000
21           T8             0.101995      0.101028      0.000000
22    Tdewpoint             0.117758      0.083128      0.000000
23           T6             0.236425      0.217292      0.000000
24           T3             0.290627      0.288087      0.000000
25         RH_1             0.553547      0.519525      0.017880

# QUESTION 12

In [22]:
x = Energy['T2']
y = Energy['T6']
array = np.array([x])
x_feature = array.reshape(-1,1)

In [23]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x_feature,y, test_size=0.3)

In [24]:
linear_model = LinearRegression()
linear_model.fit(x_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [25]:
predicted_values=linear_model.predict(x_test)

In [26]:
from sklearn.metrics import r2_score
r2_score=r2_score(y_test, predicted_values)
round(r2_score, 3)

0.65

# The no 20, i dont get the question exactly so i didnt work on it

With lasso regression find the rmse